#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<USAGE
Usage: $(basename "$0") [project-path]

Generate deterministic manual test runbook from Acceptance_Test_Cases.md.
Default project path is repository root.
Example: $(basename "$0") .
USAGE
}

log() {
  printf '[generate-manual-test-script] %s\n' "$1"
}

die() {
  log "ERROR: $1"
  exit "${2:-1}"
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  usage
  exit 0
fi

if [ "$#" -gt 1 ]; then
  usage
  exit 1
fi

project_path="${1:-.}"
cases_file="$project_path/08-quality/Acceptance_Test_Cases.md"
out_file="$project_path/08-quality/Manual_Test_Script.md"

[ -f "$cases_file" ] || die "missing acceptance test cases file: $cases_file"

rows_file="$(mktemp)"
trap 'rm -f "$rows_file"' EXIT

awk -F'|' '
  BEGIN { count=0 }
  /^\|/ {
    c1=$2; c2=$3; c3=$4; c4=$5
    gsub(/^[[:space:]]+|[[:space:]]+$/, "", c1)
    gsub(/^[[:space:]]+|[[:space:]]+$/, "", c2)
    gsub(/^[[:space:]]+|[[:space:]]+$/, "", c3)
    gsub(/^[[:space:]]+|[[:space:]]+$/, "", c4)

    if (c1 == "Test ID" || c1 == "---" || c1 == "") next

    count++
    printf "%d|%s|%s|%s|%s\n", count, c1, c2, c3, c4
  }
  END {
    if (count == 0) exit 9
  }
' "$cases_file" > "$rows_file" || {
  rc=$?
  if [ "$rc" -eq 9 ]; then
    die "no test rows found in $cases_file"
  fi
  die "failed to parse $cases_file"
}

cat > "$out_file" <<HEADER
# Manual Test Script

## Command Context

- Generated by command: prepare manual test
- Actor:
- Generated at (UTC): $(date -u +%Y-%m-%dT%H:%M:%SZ)

## Preflight

- [ ] Access required environments
- [ ] Test data prepared
- [ ] Services available

## Ordered Test Steps

| Order | Test ID | Scenario | Steps | Expected Result |
| --- | --- | --- | --- | --- |
HEADER

while IFS='|' read -r order test_id requirement_ref steps expected; do
  printf '| %s | %s | %s | %s | %s |\n' "$order" "$test_id" "$requirement_ref" "$steps" "$expected" >> "$out_file"
done < "$rows_file"

cat >> "$out_file" <<FOOTER

## Result Recording Rules

- Log outcomes in Manual_Test_Execution_Log.md.
- Report failures with command:
  - submit manual test failed: <title> | severity=<critical|high|medium|low> | details=<text>
- Link every failure to an MTI-* issue.
FOOTER

# TODO: include optional section generation for environment-specific setup steps.
log "Generated $out_file"
